### PR TITLE
Add Support for XCFrameworks

### PR DESCRIPTION
**Pull request by originalWho**
Following up a Pull Request from the original repository (tmspzz/Rome#247) to add support for XCFrameworks in the Fastlane plugin

* Added `usexcframeworks` option
* Updated input parameters validation
* Updated `README.md`
* Bumped version to `0.3.9`

### CODE REVIEW

**Review by tmspzz — APPROVED** [review]

**Comment by tmspzz** [comment]
@originalWho all done! thanks!

**Comment by deberle** [comment]
@tmspzz I would love to see this as a release. I believe it is the last obstacle to migrating our app to xcframeworks.

**Comment by tmspzz** [comment]
@deberle I don't recall I have to do anything to make a new release. Can you tell me where to look?

**Comment by tmspzz** [comment]
@deberle Forget that, I do recall. I have to make a new gem release

**Comment by tmspzz** [comment]
Released as version 0.4.0 https://rubygems.org/gems/fastlane-plugin-rome/versions/0.4.0

**Pull request merged**
